seed: 1
max_epoch: 50
batch_size: 1024
gpus: [0,1]
cross_val_count: 5
log_to_mlflow: True

datasets:
  - name: SantanderCustomerSatisfaction
    batch_size: 512
  - name: Cardiovascular-Disease-dataset
  - name: default_of_credit_card_clients
    batch_size: 512
  - name: philippine
    batch_size: 128
  - name: INNHotelsGroup
  - name: taiwanese_bankruptcy_prediction
    batch_size: 512
  - name: naticusdroid+android+permissions+dataset
    batch_size: 512
  - name: dabetes_130-us_hospitals
  - name: FOREX_audsgd-hour-High
  - name: imdb_drama

models:
  - name: amformer
  - name: modernNCA
  - name: tabr
  - name: danets
  - name: mlp_plr
  - name: PFN-v2
  - name: realmlp
  - name: t2gformer
  - name: tabm
  - name: tabnet
  - name: tangos
  - name: tabcaps

