task_type: classification
seed: 1
max_epoch: 50
batch_size: 1024
gpu: 0
cross_val_count: 5


datasets: [
  bank,
  adult,
  Telecom_Churn_Dataset,
  customer_satisfaction_in_airline,  
]

datasets: [
  INNHotelsGroup,
  taiwanese_bankruptcy_prediction,
  naticusdroid+android+permissions+dataset,
]

models:
  - name: amformer
  - name: danets
  - name: mlp_plr
  - name: PFN-v2
  - name: realmlp
  - name: t2gformer
  - name: tabm
  - name: tabnet
  - name: tangos
  - name: tabcaps
  - name: modernNCA
  - name: tabr
  # - name: excelformer
  #   batch_size: 264
  # - name: protogate
  #   batch_size: 128
  # - name: tabcaps
  # - name: grande
  # - name: trompt
  # - name: bishop
  # - name: tabr
  # - name: modernNCA