task_type: classification
seed: 1
max_epoch: 50
batch_size: 1024
gpus: [0,1,2]
cross_val_count: 5

datasets:
  - name: SantanderCustomerSatisfaction
  # - name: SEA_50

  # - name: hcdr_main
  #   batch_size: 512
  # - name: SantanderCustomerSatisfaction
  #   batch_size: 32
  # - name: imdb_drama
  #   batch_size: 4



too_large_datasets:
  [
    imdb_drama,
    hcdr_main,
    SantanderCustomerSatisfaction
  ]

high_scores_datasets:
  [
    customer_satisfaction_in_airline,
    Telecom_Churn_Dataset,
    adult,
    electricity,
    mobile_c36_oversampling,
    bank,
  ]

datsets_to_renew:
  [
    default_of_credit_card_clients,
    philippine,
    INNHotelsGroup,
    taiwanese_bankruptcy_prediction,
    naticusdroid+android+permissions+dataset,
  ]

models:
  - name: amformer
  - name: modernNCA
  - name: tabr
  - name: danets
  - name: mlp_plr
  - name: PFN-v2
  - name: realmlp
  - name: t2gformer
  - name: tabm
  - name: tabnet
  - name: tangos
  - name: tabcaps
